/* LOGIN */
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

/* COMPANIES */
export const GET_COMPANIES_LIST = 'GET_COMPANIES_LIST'
export const GET_CONTACTS_LIST = 'GET_CONTACTS_LIST'
export const GET_ASSETS_LIST = 'GET_ASSETS_LIST'
export const GET_LEAD_LIST = 'GET_LEAD_LIST'

/* SIGNUP */
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
